// This file will be auto-generated by Supabase CLI
// Run: npm run supabase:generate-types
// For now, we'll create a base type structure

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string
          name: string
          slug: string
          industry: string | null
          size_band: string | null
          timezone: string
          is_active: boolean
          plan_tier: string
          billing_email: string | null
          billing_metadata: Json
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['organizations']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['organizations']['Insert']>
      }
      profiles: {
        Row: {
          id: string
          organization_id: string
          email: string
          full_name: string | null
          role: 'org_admin' | 'campaign_admin' | 'editor' | 'viewer'
          avatar_url: string | null
          last_login_at: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      campaigns: {
        Row: {
          id: string
          organization_id: string
          created_by: string
          name: string
          description: string | null
          status: 'draft' | 'scheduled' | 'active' | 'completed' | 'archived'
          awareness_event_id: string | null
          start_at: string | null
          end_at: string | null
          primary_category: string | null
          tags: string[]
          metadata: Json
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['campaigns']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['campaigns']['Insert']>
      }
      calendar_events: {
        Row: {
          id: string
          organization_id: string | null
          title: string
          description: string | null
          category: string
          start_date: string
          end_date: string | null
          is_all_day: boolean
          scope: 'global' | 'organization'
          tags: string[]
          metadata: Json
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['calendar_events']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['calendar_events']['Insert']>
      }
      templates: {
        Row: {
          id: string
          organization_id: string | null
          name: string
          description: string | null
          category_id: string | null
          template_type: string
          base_layout: Json
          sample_content: Json
          is_global: boolean
          is_locked: boolean
          tags: string[]
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['templates']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['templates']['Insert']>
      }
      brand_kits: {
        Row: {
          id: string
          organization_id: string
          name: string
          primary_color: string
          secondary_color: string
          accent_color: string | null
          font_family_heading: string
          font_family_body: string
          logo_url: string | null
          additional_styles: Json
          is_default: boolean
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['brand_kits']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['brand_kits']['Insert']>
      }
      channels: {
        Row: {
          id: string
          organization_id: string
          type: 'slack' | 'teams' | 'email' | 'intranet' | 'tv_signage'
          name: string
          is_enabled: boolean
          config: Json
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['channels']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['channels']['Insert']>
      }
      engagement_events: {
        Row: {
          id: string
          organization_id: string
          campaign_id: string
          campaign_channel_id: string | null
          profile_id: string | null
          event_type: string
          event_value: string | null
          metadata: Json
          occurred_at: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['engagement_events']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['engagement_events']['Insert']>
      }
    }
    Views: {}
    Functions: {
      get_current_organization_id: {
        Args: Record<string, never>
        Returns: string
      }
    }
    Enums: {}
  }
}
